inherit_from: .rubocop_todo.yml


# Custom Cop Config
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'bin/{rails,rake}'
    - 'app/helpers/*'
    - 'app/channels/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'test/**/*'
# Extended LineLength to 130
Layout/LineLength:
  Max: 100

# Selected brackets as default SymbolArray Style
Style/SymbolArray:
  EnforcedStyle: brackets

# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 43

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 13

# Custom Exclude Config

# Added exclude to MixinUsage for two bin files.
# 'Setup' uses 'include' statement as top level. Excluded reason: Auto-gen file.
# 'Update' uses 'include' statement as top level. Excluded reason: Auto-gen file.
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'


# Added exclude to ClassAndModuleChildren for test .rb file.
# 'test_helper.rb' uses compact class statement 'ActiveSupport::TestCase'. Excluded reason: Auto-gen file.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'test/test_helper.rb'
    - 'app/channels/**/*'


# Added exclude to Documentation for multiple files.
# 'application_helper.rb' has an empty-body module. Excluded reason: Excluded reason: Cant add documentation to empty module.
# 'welcome_helper.rb' has an empty-body module. Excluded reason: Cant add documentation to empty module.
# 'application_mailer.rb' has none top-level class documentation. Excluded reason: Auto-gen file.
# 'application_record.rb' has none top-level class documentation. Excluded reason: Auto-gen file.

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/welcome_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'app/models/*'


# Default Cop Adds
# This Cops where added to Rubocop by the default installation but are not configured by default.
# Enabled them as true. Suggested in Rubocop Autoconfig command.

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
